'use strict';

// Builds the runtime mirror of the built-in palette library:
//
//   renderer/data/palettes.json          canonical data (edit here)
//   renderer/js/studio/palettes-data.js  the runtime mirror (UMD, sync)
//
//   node scripts/palettes-build.js
//     [--json <file>] [--table <file>] [--check]
//
// `--check` writes nothing and fails when the committed files are stale.

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const DEFAULT_JSON = path.join(ROOT, 'renderer', 'data', 'palettes.json');
const DEFAULT_TABLE = path.join(ROOT, 'renderer', 'js', 'studio', 'palettes-data.js');

const ID_RE = /^[A-Za-z][A-Za-z0-9]*$/;
const HEX_RE = /^#[0-9a-f]{6}$/;

function fail(message) {
  const error = new Error(message);
  error.code = 'palettes-invalid';
  throw error;
}

function validate(doc) {
  if (!doc || typeof doc !== 'object' || Array.isArray(doc)) fail('palettes.json: root must be an object');
  if (doc.format !== 'telopmotion-palettes') fail(`palettes.json: format must be 'telopmotion-palettes' (got ${JSON.stringify(doc.format)})`);
  if (doc.version !== 1) fail(`palettes.json: version must be 1 (got ${JSON.stringify(doc.version)})`);
  if (!Array.isArray(doc.palettes) || !doc.palettes.length) fail('palettes.json: palettes must be a non-empty array');
  const seen = new Set();
  doc.palettes.forEach((entry, index) => {
    const where = `palettes[${index}]`;
    if (!entry || typeof entry !== 'object' || Array.isArray(entry)) fail(`${where}: entry must be an object`);
    const keys = Object.keys(entry).sort().join(',');
    if (keys !== 'colors,id,name') fail(`${where}: keys must be exactly colors,id,name (got ${keys})`);
    if (typeof entry.id !== 'string' || !ID_RE.test(entry.id)) fail(`${where}: id must match ${ID_RE}`);
    if (seen.has(entry.id)) fail(`${where}: duplicate id '${entry.id}'`);
    seen.add(entry.id);
    if (typeof entry.name !== 'string' || !entry.name.trim()) fail(`${where} (${entry.id}): name must be a non-empty string`);
    if (!Array.isArray(entry.colors) || entry.colors.length !== 10) {
      fail(`${where} (${entry.id}): colors must be an array of 10 hex strings`);
    }
    entry.colors.forEach((color, slot) => {
      if (typeof color !== 'string' || !HEX_RE.test(color)) {
        fail(`${where} (${entry.id}) slot ${slot + 1}: '${color}' must be lowercase #rrggbb`);
      }
    });
  });
  return doc;
}

function loadJson(jsonPath) {
  let text;
  try {
    text = fs.readFileSync(jsonPath, 'utf8');
  } catch {
    fail(`cannot read ${jsonPath}`);
  }
  let doc;
  try {
    doc = JSON.parse(text);
  } catch {
    fail(`cannot parse ${jsonPath} as JSON`);
  }
  return { doc: validate(doc), text };
}

function tableModule(doc) {
  return [
    '// Generated by scripts/palettes-build.js — do not edit by hand.',
    '// The runtime mirror of renderer/data/palettes.json (a UMD module so the',
    '// renderer can read it synchronously).',
    '(function (root, factory) {',
    "  if (typeof module === 'object' && module.exports) module.exports = factory();",
    '  else {',
    '    root.SA = root.SA || {};',
    '    root.SA.palettesData = factory();',
    '  }',
    "})(typeof self !== 'undefined' ? self : this, function () {",
    "  'use strict';",
    `  return ${JSON.stringify(doc)};`,
    '});',
    '',
  ].join('\n');
}

function writeFileIfChanged(file, text) {
  let current = null;
  try {
    current = fs.readFileSync(file, 'utf8');
  } catch {
    current = null;
  }
  if (current === text) return false;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, text, 'utf8');
  return true;
}

function build(options) {
  const opts = options || {};
  const jsonPath = opts.json || DEFAULT_JSON;
  const tablePath = opts.table || DEFAULT_TABLE;
  const { doc } = loadJson(jsonPath);
  const jsonText = `${JSON.stringify(doc, null, 2)}\n`;
  const tableText = tableModule(doc);
  if (opts.check) {
    const problems = [];
    try {
      if (fs.readFileSync(jsonPath, 'utf8') !== jsonText) problems.push(`${jsonPath} is not normalized (run node scripts/palettes-build.js)`);
    } catch {
      problems.push(`${jsonPath} is unreadable`);
    }
    try {
      if (fs.readFileSync(tablePath, 'utf8') !== tableText) problems.push(`${tablePath} is stale (run node scripts/palettes-build.js)`);
    } catch {
      problems.push(`${tablePath} is missing (run node scripts/palettes-build.js)`);
    }
    if (problems.length) {
      const error = new Error(`palettes are stale:\n  ${problems.join('\n  ')}`);
      error.problems = problems;
      throw error;
    }
    return { doc, paths: { json: jsonPath, table: tablePath }, changed: { json: false, table: false } };
  }
  const changed = {
    json: writeFileIfChanged(jsonPath, jsonText),
    table: writeFileIfChanged(tablePath, tableText),
  };
  return { doc, paths: { json: jsonPath, table: tablePath }, changed };
}

function main(argv) {
  const flags = {};
  for (let i = 0; i < argv.length; i += 1) {
    const value = argv[i];
    if (value.startsWith('--')) {
      const key = value.slice(2);
      const next = argv[i + 1];
      if (!next || next.startsWith('--')) flags[key] = true;
      else {
        flags[key] = next;
        i += 1;
      }
    }
  }
  try {
    const result = build({
      json: flags.json === true ? null : flags.json,
      table: flags.table === true ? null : flags.table,
      check: !!flags.check,
    });
    console.log(`palettes: ${result.doc.palettes.length} palettes`);
    console.log(`  json:  ${result.paths.json}${result.changed.json ? ' (written)' : ' (unchanged)'}`);
    console.log(`  table: ${result.paths.table}${result.changed.table ? ' (written)' : ' (unchanged)'}`);
    return 0;
  } catch (error) {
    console.error(`palettes: ${error.message}`);
    return 1;
  }
}

if (require.main === module) process.exit(main(process.argv.slice(2)));

module.exports = { validate, loadJson, tableModule, build };
